version: "3.8" 

volumes:
        db_volume:
                name: Postges_volume


services:
        postgres:
                image: postgres
                container_name: Postgres_DB
                restart:  always
                environment:
                        - TZ=Europe/Moscow 
                        - POSTGRES_USER=${POSTGRES_USER}
                        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                        - POSTGRES_DB=${POSTGRES_DB}
                ports:
                        - 5432:5432
                volumes:
                        - db_volume:/var/lib/postgresql/data
        cod_bot:

